### ISSUE TITLE
Extend the PeopleAPI (WIP) to actually work and return all results

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/PittAPI#10]
There is currently a PeopleAPI that is partially developed that utilizes find.pitt.edu to scrape information about a given query. Finish the rest and return all results!

**Comment by dzheng256** [comment]
can i try this one?

**Comment by vonbearshark** [comment]
@dzheng256 , I just told @GavinFreud he could take this one on Slack.

You did an awesome job with the ML visual, though, it would be really great if you could do something similar with a new dataset. Personally, I think it would be awesome if we could have an analysis of the city police data.

**Comment by dzheng256** [comment]
sounds good

**Comment by RitwikGupta** [comment]
@dzheng256 @vonbearshark There's no reason why two people can't take this one! There are a lot of things to put in this API.

**Comment by vonbearshark** [comment]
whoops. Sure. I'll co-assign @dzheng256

**Comment by timparenti** [comment]
Just worth keeping in mind as it might affect your development, find.pitt.edu requires a CAPTCHA after ~3 queries from off-campus IPs.

**Comment by RitwikGupta** [comment]
@timparenti The current method I have bypasses CAPTCHA

**Comment by GavinFreud** [comment]
@vonbearshark looks like @dzheng256 has got this under control. Do you mind assigning him to the issue? I'll look around for some other stuff that I can do for the API

**Comment by vonbearshark** [comment]
Sure. I'll assign him when he accepts the invitation. I'll tag you in another we need help on as soon as a PR is merged (should be later this week at the latest--it's already subbed).

**Comment by dzheng256** [comment]
@vonbearshark whoops, accepted it
