### ISSUE TITLE
IndexError when getting extra details for section

### ISSUE THREAD

**Issue by maxdudek** [Pitt-CSC/PittAPI#108]
The function at line 230 of course.py could throw an IndexError if the parameter `text` does not contain the string `' :'` 

The function should look like:
```python
def __extract_data_past_colon(text: str) -> str:
        if ': ' in text:
            return text.split(': ')[1]
        else:
            return text
```

I was getting this issue for some reason and this fixed it

**Comment by azharichenko** [comment]
So the issue is to do with scraping through multiple class attributes, for what it seems. I'd don't believe that is the full solution, but was on the right track. I'm currently investigating it.
