### ISSUE TITLE
Create a DiningAPI

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/PittAPI#11]
The Pitt legacy mobile website shows if the dining halls are currently open or not: https://m.pitt.edu/dining/. Find the place where they're getting this info from, hook into it directly, and create an API to return the statuses for all dining places.

**Comment by kaidawkins** [comment]
yo this is mad helpful. and a good start for dining info until we can figure out how to get all the data we need.

**Comment by vonbearshark** [comment]
@kaidawkins we had some interest in working on this from someone else--would you like to be co-assigned to this Issue and help it along? You have some Python experience

**Comment by kaidawkins** [comment]
yeah are we building this in python and not java?

**Comment by vonbearshark** [comment]
Yepp. This repo is all Python. I just sent you an invite to be a collaborator on this repo, if you accept I can assign you

**Comment by kaidawkins** [comment]
uhhh ok i might need a refresher for python but i'm down!

**Comment by kaidawkins** [comment]
where can i accept the invite lol still trying to figure out git

**Comment by vonbearshark** [comment]
Should be the email associated with this GH account

**Comment by Rahi374** [comment]
Is it okay for me to return the names of the dining locations in unicode or should they be ascii?
The only real offending character is é.

I have the base functionality down. Just need to wrap it into a dict, and add the Market food data.
https://github.com/Rahi374/PittAPI/tree/diningapi

**Comment by brlodi** [comment]
I'd vote to leave it as Unicode since Python has good support (although I remember IDLE being sort of broken with it for a long time), unless we run into an actual problem with it.

**Comment by RitwikGupta** [comment]
Unicode. Actually, if you want to go through the repo and enforce proper Unicode encoding on all strings, that would be amazing.

**Comment by Rahi374** [comment]
@RitwikGupta Does this mean that all the dictionary keys should be changed to unicode?

**Comment by RitwikGupta** [comment]
@Rahi374 Yes please. As you can see the Python 2 is causing my string handling to be **_very_** hacky, so getting some proper universal Unicode handling across the board would be 🙏

**Comment by RitwikGupta** [comment]
I'll make a separate issue for it and assign it to you!

**Comment by Rahi374** [comment]
@RitwikGupta Hahaha okay. Sure!

Also I'm concerned that the dict keys are going to be hideous, for example: u'Caf\xe9 at the Pete - Petersen Events Center Food Court'
I think I'll string-process the name to simplify it and use that as a key to another dict with name, (open) status, and store hours. That way we can have a get_dining_loation_by_name()

**Comment by RitwikGupta** [comment]
Let's move this discussion to #17
