### ISSUE TITLE
Courses HTML Page is updated so scraping is incorrect

### ISSUE THREAD

**Issue by varughese** [Pitt-CSC/PittAPI#119]
https://github.com/Pitt-CSC/PittAPI/blob/99bef258517ae539bdec8fb67cad13cecbbb58a3/PittAPI/course.py#L265

I think the section HTML page changed, because `data[2]` no longer contains units. So I am pretty sure a couple of the other ones are incorrect as well

**Comment by azharichenko** [comment]
It's now resolved. It will be out with version 1.0
