### ISSUE TITLE
Write unit tests for all functions

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/PittAPI#12]
There is currently 0% coverage and we don't know what breaks. All functions have to be manually tested. Write a test gradle for the repo.

**Comment by mbabatunde** [comment]
How exactly would one go about doing this? Cause I know of building Java projects with gradle, but not for Python

**Comment by RitwikGupta** [comment]
@mbabatunde This guide is pretty good! http://docs.python-guide.org/en/latest/writing/tests/

**Comment by mbabatunde** [comment]
Awesome! I'll look at it and try to write some tests for the functions

**Comment by Rahi374** [comment]
I'll take this one.

**Comment by Rahi374** [comment]
Wait I'm stumped as to how we should test that the functions are doing what they're supposed to do?
Like CourseAPI#get_courses_by_req()

**Comment by RitwikGupta** [comment]
@Rahi374 Make sure that the call does not error out and that a proper JSON response is returned!

**Comment by Rahi374** [comment]
That's it?

**Comment by RitwikGupta** [comment]
Yep!
