### ISSUE TITLE
Making the package name lowercase

### ISSUE THREAD

**Issue by azharichenko** [Pitt-CSC/PittAPI#120]
I find that the current usage is not very intuitive since the package name is case sensitive and makes typing it a hassle, as shown below.
```python
from PittAPI import course
```
Instead, let's just make it all lowercase so that typing and adding the package is a breeze, and follows the convention most other packages follow. 
```python
from pittapi import course
```

Note: This is just effecting the users use of the package and don't reflect a change of the name you use to install through pip. Essentially this will still hold `pip install PittAPI`

**Comment by RitwikGupta** [comment]
Go for it. This would actually make it fit the standard, right now it's not compliant. https://www.python.org/dev/peps/pep-0008/#package-and-module-names
