### ISSUE TITLE
re-write tests for lab to mock requests

### ISSUE THREAD

**Issue by nij-patel** [Pitt-CSC/PittAPI#173]

**Comment by tianyizheng02** [comment]
@Steven-Jarmell already does this in #159, but that PR hasn't been approved and merged yet. That PR also removes the mocked tests for the people module, so we'll need to exclude that change from the PR if we wanna merge that one.

**Comment by nij-patel** [comment]
I think Steven might be busy right now, so I was planning on merging those changes through here

potentially with the new devs being onboarded soon

**Comment by Steven-Jarmell** [comment]
@tianyizheng02 We can close this one too

**Comment by tianyizheng02** [comment]
@nij-patel Since we've merged Steven's PR, we no longer need the `173-re-write-tests-for-lab-to-mock-requests` branch
