### ISSUE TITLE
Parallelize People calls

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/PittAPI#19]
The PeopleAPI currently synchronously loops in chunks of 10 to get data. The Requests API lets you make a pool of connections that not only keep one connection alive for re-use, but can be made asynchronously! Switch the PeopleAPI to use this async feature.

**Comment by Rahi374** [comment]
Is there a reason why the PeopleAPI and the LaundryAPI use curl instead of requests?

**Comment by dzheng256** [comment]
@RitwikGupta can i try this one? @Rahi374 Ritwik started off the PeopleAPI with curl, so I left it like that. Guess we're switching to requests now.

**Comment by RitwikGupta** [comment]
@dzheng256 Yeah go for it. Also, @Rahi374, there was some reason for it that I forgot now.

**Comment by RitwikGupta** [comment]
Closed by #27
