### ISSUE TITLE
pittapi.pittcsc.org doesn't exist

### ISSUE THREAD

**Issue by rohit-ganguly** [Pitt-CSC/PittAPI#207]
The URL in the GitHub project doesn't resolve to anything

**Comment by tianyizheng02** [comment]
Did the link ever exist?

**Comment by timparenti** [comment]
> Did the link ever exist?

I don't see any signs that it ever did.  I seem to recall that a project website may have once been planned for this URL, but never happened.

Simplest solution would be for a repository owner to change the website in the repository details to either remove this reference or point more generically to just [pittcsc.org](https://pittcsc.org/).  There is no such reference in the repository itself.
