### ISSUE TITLE
Write unit tests for PeopleAPI

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/PittAPI#29]
As stated, also add documentation.

**Comment by azharichenko** [comment]
I found a simple to fix issue inside of `people.py` on line 51 there is  `n_cores = multiprocessing.cpu_count()` issue is that `multiprocessing` isn't imported and not sure if you're keeping this or getting rid of it.

**Comment by RitwikGupta** [comment]
Lol I forgot to delete that line somehow. Can you make a PR to get rid of it?

**Comment by azharichenko** [comment]
Yeah, not a problem #31. :smile:

**Comment by dzheng256** [comment]
close? @RitwikGupta
