### ISSUE TITLE
(Completely irrelevant) Alex, join the CSC Slack

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/PittAPI#30]
@azharichenko Join the Pitt Computer Science Club Slack here: http://pitt-csc-slackin.herokuapp.com/
If you can't join comment your email and I'll add you manually.
Join #clubproject and anything you find interesting.

I don't have your contact info so this is my only way of communicating

**Comment by brlodi** [comment]
I think he'd need a Pitt email to be able to auto-join

**Comment by RitwikGupta** [comment]
I'll add him manually then!

**Comment by azharichenko** [comment]
My email is `alex.zharichenko@quantumcode.io`.

**Comment by RitwikGupta** [comment]
Invited.
