### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/PittAPI#38]
It's getting weird and complicated trying to support both 2 and 3 in one library.

To embrace the future (technically the present), I move to drop Python 2 support.

**Comment by RitwikGupta** [comment]
Biggest thing would be to handle Unicode properly. This is the bane of my existence.

**Comment by azharichenko** [comment]
I fully agree with this. Especially because all the Unicode nonsense would drop out quickly and python 2 has only a could years before PSF is dropping support. https://pythonclock.org

**Comment by RitwikGupta** [comment]
Let's get one more in support and we're dropping it

**Comment by dzheng256** [comment]
yeah I agree as well.

**Comment by RitwikGupta** [comment]
Cool, Python 2 support now officially dropped.
