### ISSUE TITLE
Create a News API

### ISSUE THREAD

**Issue by RitwikGupta** [Pitt-CSC/PittAPI#46]
I found this URL: https://m.pitt.edu/news/index.json?feed=main_news&id=&_object=kgoui_Rcontent_I0_Rcontent_I0&_object_include_html=1

Gets us all the Pitt news. There are different feeds that go into the `feed` URL path paramater:
```python
feeds = (
    "main_news",  # pitt.com main news
    "cssd",  # student announcements, stuff that goes on My Pitt
    "news_chronicle",  # the Pitt Chronicle news
    "news_alerts"  # crime alerts
)
```

**Comment by Rahi374** [comment]
The JSON response looks like it's in the same format as the data that I retrieved for the DiningAPI.

**Comment by RitwikGupta** [comment]
It is. They use Kurogi to provide these services so the responses are similar.

**Comment by Rahi374** [comment]
Ah I see.
I started working on this one.

**Comment by Rahi374** [comment]
Oh wait but the only data we get from the JSON is the name of the news event/article and a link to it.
It it enough to just return an array of dicts of article-name and url pairs?

**Comment by RitwikGupta** [comment]
Yes, that's perfect! Please also write tests as you go along.

**Comment by Rahi374** [comment]
Tests... okay...

**Comment by RitwikGupta** [comment]
Just follow the format of one of the tests in `tests/`! The Dining tests might be the best for you.

**Comment by Rahi374** [comment]
Hmm. I'll try.

**Comment by RitwikGupta** [comment]
Closed! 🎉
