### ISSUE TITLE
make PittAPI actually an API

### ISSUE THREAD

**Issue by eas141** [Pitt-CSC/PittAPI#47]
Currently PittAPI is essentially a collection of functions in classes.  Gold!  

However, it would be more useful if it was hosted on, say, an AWS lambda.

**Comment by azharichenko** [comment]
We have with this library built a [web wrapper](https://github.com/Pitt-CSC/PittAPIWebWrapper) for it. This is where the API will really become an API.

**Comment by azharichenko** [comment]
@RitwikGupta Though now that I think about it. Wouldn't the name `PittData` be a better name for this library especially because it's designed to essentially fetch the data while `PittAPIWebWrapper` is actually the API?

**Comment by RitwikGupta** [comment]
@eas141 Erik, as Alex mentioned, the PittAPIWebWrapper exposes the entire PittAPI through a REST interface. This will be hosted on CS department servers soon for all your language agnostic needs.

@azharichenko This project provides an API for Python, so the name is accurate. The wrapper just exposes the API via a REST API for language agnostic needs. I don't think a name change is necessary 😄

**Comment by azharichenko** [comment]
Yeah, that makes sense @RitwikGupta :+1:
