### ISSUE TITLE
README.md issues

### ISSUE THREAD

**Issue by aop4** [Pitt-CSC/PittAPI#91]
Hey, I was messing around with your example use cases in README.md and noticed a few things. First, there's a call for a deprecated function in there. The line
`big_dict = course.get_courses(term="2177", code="CS")`
should be
`big_dict = course.get_classes(term="2177", code="CS")` since `get_courses()` is deprecated.
You also make a call to `course.get_course()` when I believe you mean to call `course.get_courses()`, since `course.get_course()` doesn't exist (sorry, but it's a little confusing when there's a `get_class()`).

I'm just working with the course module right now, but you should probably take a look through the examples in README.md. In particular, all the examples related to dining don't seem to be working right now (for me, the first 3 return empty lists, and get_location_by_name isn't a valid function name)--not sure if that's still a work in progress. I just installed and upgraded the package with Pip, so maybe the issues with dining.py have something to do with that version not being updated.

Anyway, sorry for the lengthy thing. Awesome job on this API overall.

**Comment by aop4** [comment]
@RitwikGupta thanks! That will benefit people like me who are sometimes too lazy to read the docs!

**Comment by RitwikGupta** [comment]
@aop4 The Dining API works fine for me. It just takes a while (>30 sec at times) because Pitt's servers run on a potato. If you create an application on top of this, implement a thin caching/memoization layer for these requests.

**Comment by aop4** [comment]
Ya, I'm seeing that as well now; I think I didn't wait long enough. And get_location_by_name() didn't work simply because it's been commented out, so I guess the PyPI version is pretty much the same. Thanks for clarifying that!
